{
 "title": "Dependency-Track",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current Heap Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"}) / sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Avg. Events Published",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(alpine_events_published_total{instance=\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. Notifications Published",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(alpine_notifications_published_total{instance=\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Java Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$instance\"}",
     "legendFormat": "{{vendor}} {{version}}"
    }
   ]
  },
  {
   "title": "Current Non-Heap Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"}) / sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\",area=\"heap\"} > 0",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"heap\"}) > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\",area=\"nonheap\"} > 0",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"nonheap\"}) > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\",area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Average GC Pause Duration",
   "type": "timeseries",
   "description": "Average duration of garbage collection pauses caused by the JVM garbage collector.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{instance=\"$instance\"}[1m]) / rate(jvm_gc_pause_seconds_count{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Average GC Memory Allocation",
   "type": "timeseries",
   "description": "Average amount of memory allocated by the JVM garbage collector.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Database Connections: Transactional",
   "type": "timeseries",
   "description": "Number of connections in the transactional connection pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"$instance\",pool=\"transactional\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\",pool=\"transactional\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\",pool=\"transactional\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\",pool=\"transactional\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Database Connections: Non-Transactional",
   "type": "timeseries",
   "description": "Number of connections in the non-transactional connection pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"$instance\",pool=\"non-transactional\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\",pool=\"non-transactional\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\",pool=\"non-transactional\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\",pool=\"non-transactional\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "timeseries",
   "description": "Average number of database operations per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(datanucleus_datastore_writes_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "Writes"
    },
    {
     "expr": "rate(datanucleus_datastore_reads_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "timeseries",
   "description": "Average number of database queries per second.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(datanucleus_queries_executed_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(datanucleus_queries_failed_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Database Transactions",
   "type": "timeseries",
   "description": "Average number of database transactions per second.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(datanucleus_transactions_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(datanucleus_transactions_committed_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "Committed"
    },
    {
     "expr": "rate(datanucleus_transactions_rolledback_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "Rolled Back"
    }
   ]
  },
  {
   "title": "Average Connection Acquisition Duration",
   "type": "timeseries",
   "description": "Average time it takes for a thread to acquire a connection from the database connection pool.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(hikaricp_connections_acquire_seconds_sum{instance=\"$instance\"}[1m]) / rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\"}[1m])) > 0",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Average Connection Usage Duration",
   "type": "timeseries",
   "description": "Average time of connections being used before being returned to the connection pool.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(hikaricp_connections_usage_seconds_sum{instance=\"$instance\"}[1m]) / rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\"}[1m])) > 0",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Average Connection Creation Duration",
   "type": "timeseries",
   "description": "Average time it takes to create a new database connection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(hikaricp_connections_creation_seconds_sum{instance=\"$instance\"}[1m]) / rate(hikaricp_connections_creation_seconds_count{instance=\"$instance\"}[1m])) > 0",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "ORM Cache Entries",
   "type": "timeseries",
   "description": "Total number of entries in the caches used by the object relational mapper (ORM).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "datanucleus_cache_second_level_entries{instance=\"$instance\"}",
     "legendFormat": "L2"
    },
    {
     "expr": "datanucleus_cache_query_generic_compilation_entries{instance=\"$instance\"}",
     "legendFormat": "Generic Query Compilation"
    },
    {
     "expr": "datanucleus_cache_query_datastore_compilation_entries{instance=\"$instance\"}",
     "legendFormat": "Datastore Query Compilation"
    }
   ]
  },
  { "title": "Event System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Events Processed",
   "type": "timeseries",
   "description": "Number of events processed per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total{instance=\"$instance\", name=\"Alpine-EventService\"}[1m]) > 0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(executor_completed_tasks_total{instance=\"$instance\", name=\"Alpine-SingleThreadedEventService\"}[1m]) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Events Queued",
   "type": "timeseries",
   "description": "Total number of events queued for processing.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "executor_queued_tasks{instance=\"$instance\", name=\"Alpine-EventService\"} > 0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "executor_queued_tasks{instance=\"$instance\", name=\"Alpine-SingleThreadedEventService\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Worker Threads",
   "type": "timeseries",
   "description": "Number of active threads per worker pool.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "executor_active_threads{instance=\"$instance\", name=\"Alpine-EventService\"} > 0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "executor_active_threads{instance=\"$instance\", name=\"Alpine-SingleThreadedEventService\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Events Published",
   "type": "timeseries",
   "description": "Average number of events published per second.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(alpine_events_published_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Average Event Processing Duration",
   "type": "timeseries",
   "description": "Average time it takes to process events.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(alpine_event_processing_seconds_sum{instance=\"$instance\"}[1m]) / rate(alpine_event_processing_seconds_count{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Notifications Processed",
   "type": "timeseries",
   "description": "Number of notifications processed per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total{instance=\"$instance\", name=\"Alpine-NotificationService\"}[1m]) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Notifications Queued",
   "type": "timeseries",
   "description": "Total number of notifications queued for processing.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "targets": [
    {
     "expr": "executor_queued_tasks{instance=\"$instance\", name=\"Alpine-NotificationService\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Worker Threads",
   "type": "timeseries",
   "description": "Number of active threads per worker pool.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "targets": [
    {
     "expr": "executor_active_threads{instance=\"$instance\", name=\"Alpine-NotificationService\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Notifications Published",
   "type": "timeseries",
   "description": "Average number of events published per second. Note that this includes ALL notifications, even those for which no alert was configured.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(alpine_notifications_published_total{instance=\"$instance\"}[1m]) > 0",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Functional",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Repository Metadata Analysis Duration",
     "type": "timeseries",
     "description": "Average time taken to analyze the repository metadata for all components in a project.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(repository_meta_analyzer_task_seconds_sum{instance=\"$instance\"}[1m]) / rate(repository_meta_analyzer_task_seconds_count{instance=\"$instance\"}[1m])) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Search Index Rebuild Duration",
     "type": "timeseries",
     "description": "Average time taken to rebuild Lucene search indexes, per index type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(lucene_index_rebuild_seconds_sum{instance=\"$instance\"}[1m]) / rate(lucene_index_rebuild_seconds_count{instance=\"$instance\"}[1m])) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Retries: Sonatype OSS Index API",
     "type": "timeseries",
     "description": "Average number of retries against the Sonatype OSS Index API.\n\nNote: If OSS Index is not enabled, no data will be displayed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(resilience4j_retry_calls_total{instance=\"$instance\",name=\"ossIndexRetryer\"}[1m]) > 0",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Retries: Snyk",
     "type": "timeseries",
     "description": "Average number of retries against the Snyk API.\n\nNote: If Snyk is not enabled, no data will be displayed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(resilience4j_retry_calls_total{instance=\"$instance\",name=\"snyk-api\"}[1m]) > 0",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  }
 ]
}